spring:
  application:
    name: argus-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/moss?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

server:
  port: ${randomServerPort.value[1000,5000]}


eureka:
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
#    enabled: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
