spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0
  mail:
    host: smtp.qq.com
    username: 3135205134
    password: naocvsuitmapdcdb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: argus-server
  datasource:
    url: jdbc:mysql://localhost:3306/argus_auth?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 139.9.82.163
    port: 5672
    username: admin
    password: admin
    listener:
      direct:
        consumers-per-queue: 100

  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      properties:
        client.transport.sniff: true

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      zone-1: http://localhost:8761/eureka/
      zone-2: http://localhost:8761/eureka/

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: false
      logic-delete-value: true
      db-type: mysql
      id-type: auto
    banner: false

server:
  port: 7878

security:
  oauth2:
    resource:
      id: ${spring.application.name}
      user-info-uri: http://localhost:8989/user
