spring:
  mail:
    host: smtp.qq.com
    username: 3135205134
    password: naocvsuitmapdcdb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: argus-server
  datasource:
    url: jdbc:mysql://47.100.238.207:3306/argus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  rabbitmq:
    host: 139.9.82.163
    port: 5672
    username: guest
    password: guest
    listener:
      direct:
        consumers-per-queue: 100

  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: elasticsearch
      properties:
        client.transport.sniff: true


eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    service-url:
      zone-1: http://localhost:8761/eureka/
      zone-2: http://localhost:8761/eureka/

mybatis-plus:
  global-config:
    db-config:
      logic-not-delete-value: false
      logic-delete-value: true
      db-type: mysql

server:
  port: 7878
