server:
  port: 7777
spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.235:27017/g08
  redis:
    host: localhost
    port: 6379
  application:
    name: argus-example-eureka-client

eureka:
  client:
    region: guangzhou
    availability-zones:
      guangzhou: zone-1,zone-2
    service-url:
      zone-1: http://localhost:8761/eureka/
      zone-2: http://localhost:8761/eureka/

hystrix:
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: 15
      queueSizeRejectionThreshold: 2000


