server:
  port: 7777
spring:
  application:
    name: argus-example-eureka-client

eureka:
  client:
    region: guangzhou
    availability-zones:
      guangzhou: zone-1,zone-2
    service-url:
      zone-1: http://localhost:8761/eureka/
      zone-2: http://localhost:8761/eureka/

